package com.dataobject;

import java.util.Date;

public class TaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.id
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.task_name
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.description
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.deadline
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.finished
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    private Integer finished;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.id
     *
     * @return the value of task_info.id
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.id
     *
     * @param id the value for task_info.id
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.task_name
     *
     * @return the value of task_info.task_name
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.task_name
     *
     * @param taskName the value for task_info.task_name
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.description
     *
     * @return the value of task_info.description
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.description
     *
     * @param description the value for task_info.description
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.deadline
     *
     * @return the value of task_info.deadline
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.deadline
     *
     * @param deadline the value for task_info.deadline
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.finished
     *
     * @return the value of task_info.finished
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public Integer getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.finished
     *
     * @param finished the value for task_info.finished
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    public void setFinished(Integer finished) {
        this.finished = finished;
    }
}