package com.dao;

import com.dataobject.TaskDO;

import java.util.List;

public interface TaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    int insert(TaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    int insertSelective(TaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    TaskDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    int updateByPrimaryKeySelective(TaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Wed Apr 08 22:43:12 CST 2020
     */
    int updateByPrimaryKey(TaskDO record);

    List<TaskDO> listTasks();
}